### ISSUE TITLE
Plugin can not be parsed in gazebo 1.5.0 in ros groovy

### ISSUE THREAD

**Issue by mikegao88** [tu-darmstadt-ros-pkg/hector_quadrotor#1]
Hi, as the title indicates, the problem is that the gazebo 1.5.0 in ros groovy can not parse the plugins of the sensor and the controller modules of the simulated quadrotor, then the robot just falls down to the ground when the simulator starts. Is there anybody who takes care of this? Thanks! (By the way, the package name of gazebo in any gazebo world launch file should be modified to "gzb", otherwise it will report error and can not start, thus the service name for spawning model has also to be modified accordingly to "/gzb/spawn_urdf_model".)

**Comment by meyerj** [comment]
The default launch files shipped with the [gazebo_worlds](http://wiki.ros.org/gazebo_worlds) package in ROS groovy and in our own launch files in [hector_gazebo_worlds](http://wiki.ros.org/hector_gazebo_worlds) and in [hector_quadrotor_gazebo](http://wiki.ros.org/hector_quadrotor_gazebo) use `gazebo` as node name for the default instance. Make sure you change the `<node name="..." ...>` attribute accordingly in your own launch files as long as you do not want to run multiple instances. I have no idea where the `/gzb` prefix should come from otherwise. Most topics subscribed and advertised by gazebo are within its private namespace and have the `/<node name>` prefix.

The new [catkin](https://github.com/tu-darmstadt-ros-pkg/hector_quadrotor/tree/catkin) branch is not compatible with groovy. Make sure you cloned the default [groovy-devel](https://github.com/tu-darmstadt-ros-pkg/hector_quadrotor/tree/groovy-devel) branch of hector_quadrotor **and all it's dependencies** and that all packages have been built without errors (using `rosmake hector_quadrotor_gazebo`). Alternatively you can just install the binary packages for groovy from the ROS ubuntu repositories (`sudo apt-get install ros-groovy-hector-quadrotor`).

Regarding the plugin problem, could you post some error output from gazebo or give some more details about what you mean with "can not parse the plugins of the sensor and the controller modules of the simulated quadrotor"?

**Comment by meyerj** [comment]
Closing this as there was no response from the author.
