### ISSUE TITLE
Uncontrollable quadrotor_with_asus in Gazebo - hector_quadrotor

### ISSUE THREAD

**Issue by TSC21** [tu-darmstadt-ros-pkg/hector_quadrotor#12]
Hi,

Presented this on answers.ros.org:

http://answers.ros.org/question/182908/uncontrollable-quadrotor_with_asus-in-gazebo-hector_quadrotor/

Still looking for a solution.

Thanks in advance!

**Comment by meyerj** [comment]
Hi,

I could reproduce the problem. It is caused by the additional mass and moment of the ASUS camera, that was never tested with the new controller implementation. For some reason the Kinect model in our [hector_sensors_description](http://wiki.ros.org/hector_sensors_description) package has almost no mass, while the ASUS Xtion has a mass of 200 g.

I updated the controller settings and added some integral gain to the x/y angle (attitude) controller so that it is able to cope with the asymmetric center of gravity. Now I am able to control the drone with the ASUS camera, only directly after takeoff the quadrotor drifts a little bit until the controller counteracts.

Could you please test the [fix-12](https://github.com/tu-darmstadt-ros-pkg/hector_quadrotor/tree/fix-12) branch and confirm that it also solves the problem for you? If you have the binary packages and installed and do not want to install from source you can simply modify the ´controller.yaml´ file in package `$(rospack find hector_quadrotor_controller)/params` according to 3ce12f817f0aeb9644c4f926b82c5a991295ac17 (root privileges required).

Johannes
