### ISSUE TITLE
Using Hector Quadrotor in Gazebo 5

### ISSUE THREAD

**Issue by vikrantvm** [tu-darmstadt-ros-pkg/hector_quadrotor#27]
ros-indigo-hector-quadrotor-gazebo : Depends: ros-indigo-gazebo-plugins but it is not going to be installed
                                      Depends: ros-indigo-hector-gazebo-plugins but it is not going to be installed
                                      Depends: ros-indigo-hector-quadrotor-controller-gazebo but it is not going to be installed
                                      Depends: ros-indigo-hector-quadrotor-gazebo-plugins but it is not going to be installed
                                      Depends: ros-indigo-hector-sensors-gazebo but it is not going to be installed

I am trtying to use hector in gazebo 5 , but I get these error messages. I have installed ros-indigo-gazebo-plugins in gazebo 5 as ros-indigo-gazebo5-plugins ..How do I get around this?

**Comment by meyerj** [comment]
Gazebo 5 is not officially supported in ROS indigo and therefore hector_quadrotor and some packages it depends on are missing in the ROS binary package repositories. That's why you would need to build hector_quadrotor AND at least hector_gazebo_plugins in the [hector_gazebo](https://github.com/tu-darmstadt-ros-pkg/hector_gazebo) repository from source. Check out the [hector_quadrotor tutorials](http://wiki.ros.org/hector_quadrotor/Tutorials) in the ROS wiki and follow the "Install from source" sections.

We never tried hector_quadrotor with Gazebo 5 until now. We only did some basic tests with Gazebo 4 and that seems to work fine. Please report any new issue you might find, but I will close this one for now as the reported error is clearly related to dependency problems with the pre-built binary packages.
