### ISSUE TITLE
hector_quadrotor installation problems in ROS melodic

### ISSUE THREAD

**Issue by deBilla** [tu-darmstadt-ros-pkg/hector_quadrotor#92]
Package cannot be found when `sudo  apt-get install ros-melodic-hector-quadrotor-demo`. I even tried building it with the source but then errors from driver_base not found happen. If there are any melodic users can you guide me how to install hector_quadrotor.

**Comment by meyerj** [comment]
I am afraid that the `hector_quadrotor` repository and some of its `hector_*` dependencies have not (yet) been released for kinetic, lunar or melodic because of a lack of time.

But I was able to build everything from source (see [hector_quadrotor.rosinstall](https://github.com/tu-darmstadt-ros-pkg/hector_quadrotor/blob/kinetic-devel/hector_quadrotor.rosinstall)) with the following patches that have been merged into their respective default branches (`kinetic-devel`/`catkin`) in Ubuntu bionic with ROS melodic and Gazebo 9:

- https://github.com/tu-darmstadt-ros-pkg/hector_gazebo/pull/44
- https://github.com/tu-darmstadt-ros-pkg/hector_localization/pull/16
- https://github.com/tu-darmstadt-ros-pkg/hector_localization/commit/30bf100134a2ddf2eb8da80a82dad7d79cb8288a
- https://github.com/tu-darmstadt-ros-pkg/hector_quadrotor/commit/fca8caf36765c87d9dde77b14412d900bdd029ab
- https://github.com/tu-darmstadt-ros-pkg/hector_quadrotor/commit/0e5bffefa9bcf93089f66f797c25149d7d865961
- https://github.com/tu-darmstadt-ros-pkg/hector_quadrotor/commit/5b60ec6ce656bd5f2955d8d69ba9c1307db36af0 and
- https://github.com/tu-darmstadt-ros-pkg/hector_quadrotor/commit/8bbd11e6bd6f84a8a848b0b262a15f0526d264f5.

I have not checked yet whether there are any apparent functional issues.

**Comment by deBilla** [comment]
Thank you very much i will try it out.

**Comment by yrosascu** [comment]
Hi, @CredOz do you try? it worked?

**Comment by deBilla** [comment]
Not working... I think it's better for m to switch to a old version of
ubuntu to get it work. But actually I tried my software on a real quadcopter

**Comment by ghost** [comment]
I could install it without much of a hassle.
Perhaps now it can work on melodic)

**Comment by deBilla** [comment]
Yeah i tried it long time ago. Must be fiexed now

**Comment by haidenmcgrath** [comment]
Can anyone confirm that hector quadrotor is working on ROS melodic on Ubuntu 18.04?

**Comment by haidenmcgrath** [comment]
@CredOz @letsdoitagain @meyerj @yrosascu

**Comment by deBilla** [comment]
Nope i havent tried it in a long time.

**Comment by ghost** [comment]
yup,as i said in the previous message. it did for me. 
All i have to do was to install another package from source in the same directory. i think it was hector_localization (if not mistaken). So, yes it works just fine.

However, i am not sure about other packages it depends upon. for example: hector_mapping is released only for kinetic. i have not tried it for this package.

**Comment by pfreitasc** [comment]
I'd just like to confirm that you can indeed install it in Ubuntu 18.04 with Melodic. There are melodic versions of hector_models and hector_gazebo, and hector_quadrotor and hector_localization are compatible, if I'm not mistaken.

**Comment by EdwinMeriaux** [comment]
@letsdoitagain @PedroFrCa 
Hi, I just have an additional question.
So, you installed the hector_loclization, hector_models,  hector_gazebo, and hector_quadrotor.
But was there a hector_quadrotor_teleop for ROS Melodic? I can only find one for ROS Kinetic.

**Comment by ahmedbaza** [comment]
did you find any solution for hector_quadrotor_teleop on melodic ?

**Comment by kowais915** [comment]
I am using ROS melodic on ubuntu 18.04 and when it still says:

Could not find a package configuration file provided by
  "hector_pose_estimation" with any of the following names:

    hector_pose_estimationConfig.cmake
    hector_pose_estimation-config.cmake
